CANVAS_WIDTH = 800
CANVAS_HEIGHT = 600

UPDATE_DELAY = 33

FRUIT_SLOW_SPEED = 5
FRUIT_FAST_SPEED = 10

BASKET_LEFT = 1
BASKET_RIGHT = 2
BASKET_SPEED = 10
BASKET_MARGIN = 20

BASKET_CATCH_DISTANCE = 40